version: '3.9'
services:
  db:
    image: postgres
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_NAME=db
    restart: unless-stopped
  
  

  web:
    
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: /bin/sh -c "sh scripts/entrypoint.sh "
   
    volumes:
      - .:/basicsite
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_HOST_NAME=db
      - DJANGO_SUPERUSER_PASSWORD=faisy
    depends_on:
      - db
    # container_name: basicsite.web
