version: '3.9'
services:
  db:
    image: python:3.9
    volumes:
     - ./db.sqlite3:/basicsite/sqlite3.db
    restart: unless-stopped
  
  

  web:
    
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python3 manage.py migrate --run-syncdb &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/basicsite
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: basicsite.web